### ISSUE TITLE
Java errors in 6.10.4

### ISSUE THREAD

**Issue by jandelange** [synobsys/mendix-DragAndDropSupportWidget#5]
since I Migrate to 6.10.4 i get these errors. I deleted deployment folder but that doesn't help.

compile:
    [javac] Compiling 141 source files to C:\Users\Jan\Documents\Mendix\HTRT-main_3\deployment\run\bin
    [javac] C:\Users\Jan\Documents\Mendix\HTRT-main_3\javasource\projects\proxies\DropElement.java:157: error: cannot find symbol
    [javac] 	public final machines.proxies.Element getDropElement_Elements() throws com.mendix.core.CoreException
    [javac] 	                             ^
    [javac]   symbol:   class Element
    [javac]   location: package machines.proxies
    [javac] C:\Users\Jan\Documents\Mendix\HTRT-main_3\javasource\projects\proxies\DropElement.java:166: error: cannot find symbol
    [javac] 	public final machines.proxies.Element getDropElement_Elements(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
    [javac] 	                             ^
    [javac]   symbol:   class Element
    [javac]   location: package machines.proxies
    [javac] C:\Users\Jan\Documents\Mendix\HTRT-main_3\javasource\projects\proxies\DropElement.java:179: error: cannot find symbol
    [javac] 	public final void setDropElement_Elements(machines.proxies.Element dropelement_elements)
    [javac] 	                                                          ^
    [javac]   symbol:   class Element
    [javac]   location: package machines.proxies
    [javac] C:\Users\Jan\Documents\Mendix\HTRT-main_3\javasource\projects\proxies\DropElement.java:189: error: cannot find symbol
    [javac] 	public final void setDropElement_Elements(com.mendix.systemwideinterfaces.core.IContext context, machines.proxies.Element dropelement_elements)
    [javac]

**Comment by jandelange** [comment]
sorry close was not close page

**Comment by mgroeneweg** [comment]
Hi, I originally created this widget when working for Synobsys. I recently started migrating the widgets to 6.10.2 with a test in Mendix 7. Could you try the version distributed by ITvisors?
[](https://appstore.home.mendix.com/link/app/36773/Itvisors/Drag-and-drop-support-widget)

**Comment by mgroeneweg** [comment]
https://appstore.home.mendix.com/link/app/36773/Itvisors/Drag-and-drop-support-widget

**Comment by jandelange** [comment]
Thx. I will try.

**Comment by jandelange** [comment]
Same errors. I deleted the widget from my project and deleted the javasource but still problems.
I think getDropElement made me think it is something with the widget.

machines.proxies.Element getDropElement_Elements() throws com.mendix.core.CoreException
    [javac] 	                             ^
    [javac]   symbol:   class Element
    [javac]   location: package machines.proxies

**Comment by mgroeneweg** [comment]
It complains about a class Element which appears to exist in module Machines. Did you create or import a module Machines? If the module got deleted or renamed, the javasource was probably left behind.
